#include "../../src/iridium/air.cpp"
#include <llvm-c/BitWriter.h>
#include <llvm-c/IRReader.h>
#include <cstdio>
#include <cstdlib>
int main(int argc,char**argv)try{
 if(argc!=2||!Iridium::DynamicLLVM::init())return 2;auto c=LLVMContextCreate();
 const char source[]="define void @authoredFragment(ptr %texture, ptr %sampler) { entry: %identity = bitcast ptr %texture to ptr ret void }\n";
 auto input=LLVMCreateMemoryBufferWithMemoryRangeCopy(source,sizeof(source)-1,"authored-pointer");LLVMModuleRef m=nullptr;char*error=nullptr;if(LLVMParseIRInContext(c,input,&m,&error)){std::fprintf(stderr,"%s\n",error);LLVMDisposeMessage(error);return 3;}
 auto function=LLVMGetNamedFunction(m,"authoredFragment");auto block=LLVMGetFirstBasicBlock(function);auto identity=LLVMGetFirstInstruction(block);auto writer=LLVMCreateBuilderInContext(c);LLVMPositionBuilderBefore(writer,LLVMGetBasicBlockTerminator(block));auto f32=LLVMFloatTypeInContext(c);auto i32=LLVMInt32TypeInContext(c);auto boolean=LLVMInt1TypeInContext(c);auto ptr=LLVMPointerTypeInContext(c,0);auto v2=LLVMVectorType(f32,2);auto v4=LLVMVectorType(f32,4);auto iv2=LLVMVectorType(i32,2);LLVMTypeRef fields[]={v4,LLVMInt8TypeInContext(c)};auto result=LLVMStructTypeInContext(c,fields,2,0);LLVMTypeRef args[]={ptr,ptr,v2,boolean,iv2,boolean,f32,f32,i32};auto sampleType=LLVMFunctionType(result,args,9,0);auto sample=LLVMAddFunction(m,"air.sample_texture_2d.v4f32",sampleType);LLVMValueRef values[]={identity,LLVMGetParam(function,1),LLVMConstNull(v2),LLVMConstNull(boolean),LLVMConstNull(iv2),LLVMConstNull(boolean),LLVMConstReal(f32,0),LLVMConstReal(f32,0),LLVMConstNull(i32)};LLVMBuildCall2(writer,sampleType,sample,values,9,"sampled");auto integer=LLVMInt32TypeInContext(c);auto str=[&](const char*s){return LLVMMDStringInContext(c,s,std::strlen(s));};auto n=[&](unsigned x){return LLVMConstInt(integer,x,0);};LLVMValueRef descriptor[]={n(0),str("air.texture"),str("air.location_index"),n(0),n(1),str("air.sample"),str("air.arg_type_name"),str("texture2d<float, access::sample>")};auto parameter=LLVMMDNodeInContext(c,descriptor,8);LLVMValueRef samplerDescriptor[]={n(1),str("air.sampler"),str("air.location_index"),n(0),n(1)};LLVMValueRef params[]={parameter,LLVMMDNodeInContext(c,samplerDescriptor,5)};LLVMValueRef root[]={function,LLVMMDNodeInContext(c,nullptr,0),LLVMMDNodeInContext(c,params,2)};LLVMAddNamedMetadataOperand(m,"air.fragment",LLVMMDNodeInContext(c,root,3));
 auto bitcode=LLVMWriteBitcodeToMemoryBuffer(m);Iridium::AIR::Function translated(Iridium::AIR::Function::Type::Fragment,"authoredFragment",LLVMGetBufferStart(bitcode),LLVMGetBufferSize(bitcode));Iridium::SPIRV::Builder b;b.setVersion(1,5);b.requireCapability(Iridium::SPIRV::Capability::Shader);b.setAddressingModel(Iridium::SPIRV::AddressingModel::Logical);b.setMemoryModel(Iridium::SPIRV::MemoryModel::GLSL450);Iridium::OutputInfo info;translated.analyze(b,info);size_t size;void*bytes=b.finalize(size);FILE*f=std::fopen(argv[1],"wb");if(!f)return 4;std::fwrite(bytes,1,size,f);std::fclose(f);std::free(bytes);LLVMDisposeMemoryBuffer(bitcode);LLVMDisposeBuilder(writer);LLVMDisposeModule(m);LLVMContextDispose(c);return 0;
}catch(const std::exception&e){std::fprintf(stderr,"%s\n",e.what());return 1;}
