#include "../../src/iridium/air.cpp"
#include <llvm-c/BitWriter.h>
#include <cstdio>
#include <cstdlib>
int main(int argc,char**argv)try{
 if(argc!=4||!Iridium::DynamicLLVM::init())return 2;bool toInteger=std::strtoul(argv[1],nullptr,10);unsigned count=std::strtoul(argv[2],nullptr,10);if(count!=1&&count!=4)return 3;
 auto c=LLVMContextCreate();auto m=LLVMModuleCreateWithNameInContext("authored-bitcast",c);auto integer=LLVMInt32TypeInContext(c);auto floating=LLVMFloatTypeInContext(c);auto source=toInteger?floating:integer;auto destination=toInteger?integer:floating;if(count==4){source=LLVMVectorType(source,4);destination=LLVMVectorType(destination,4);}
 auto ft=LLVMFunctionType(LLVMVoidTypeInContext(c),&source,1,0);auto function=LLVMAddFunction(m,"authoredVertex",ft);auto writer=LLVMCreateBuilderInContext(c);LLVMPositionBuilderAtEnd(writer,LLVMAppendBasicBlockInContext(c,function,"entry"));
 auto cast=LLVMBuildBitCast(writer,LLVMGetParam(function,0),destination,"typedCast");auto one=toInteger?LLVMConstInt(integer,1,0):LLVMConstReal(floating,1.0);if(count==4){LLVMValueRef elements[]={one,one,one,one};one=LLVMConstVector(elements,4);}if(toInteger){auto zero=LLVMConstInt(integer,0,0);if(count==1)LLVMBuildInsertElement(writer,LLVMGetUndef(LLVMVectorType(integer,2)),cast,zero,"usedInteger");else LLVMBuildExtractElement(writer,cast,zero,"usedInteger");}else LLVMBuildFAdd(writer,cast,one,"usedFloat");LLVMBuildRetVoid(writer);
 auto str=[&](const char*s){return LLVMMDStringInContext(c,s,std::strlen(s));};auto n=[&](unsigned x){return LLVMConstInt(integer,x,0);};LLVMValueRef descriptor[]={n(0),str("air.vertex_input"),str("air.location_index"),n(0),n(1)};auto parameter=LLVMMDNodeInContext(c,descriptor,5);LLVMValueRef root[]={function,LLVMMDNodeInContext(c,nullptr,0),LLVMMDNodeInContext(c,&parameter,1)};LLVMAddNamedMetadataOperand(m,"air.vertex",LLVMMDNodeInContext(c,root,3));
 auto bitcode=LLVMWriteBitcodeToMemoryBuffer(m);Iridium::AIR::Function translated(Iridium::AIR::Function::Type::Vertex,"authoredVertex",LLVMGetBufferStart(bitcode),LLVMGetBufferSize(bitcode));Iridium::SPIRV::Builder b;b.setVersion(1,5);b.requireCapability(Iridium::SPIRV::Capability::Shader);b.setAddressingModel(Iridium::SPIRV::AddressingModel::Logical);b.setMemoryModel(Iridium::SPIRV::MemoryModel::GLSL450);Iridium::OutputInfo info;translated.analyze(b,info);size_t size;void*bytes=b.finalize(size);FILE*f=std::fopen(argv[3],"wb");if(!f)return 4;std::fwrite(bytes,1,size,f);std::fclose(f);std::free(bytes);LLVMDisposeMemoryBuffer(bitcode);LLVMDisposeBuilder(writer);LLVMDisposeModule(m);LLVMContextDispose(c);return 0;
}catch(const std::exception&e){std::fprintf(stderr,"%s\n",e.what());return 1;}
